spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service_provider?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: provider

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://112.74.180.80:9000/eureka/

mybatis-plus:
  mapper-locations: calsspath:com/gyg/provider/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.gyg: debug